### ISSUE TITLE
Undefined index in class.flagship-hook.php

### ISSUE THREAD

**Issue by dlaramee** [flagshipcompany/flagship-for-woocommerce#20]
Enabling WP debug because of an Error 500 (not related to this plugin), I noticed these 'PHP Notice'

```
[15-Sep-2016 15:11:33 UTC] PHP Notice:  Undefined index: setup.filters in /var/www/website_path/wp-content/plugins/flagship-for-woocommerce/includes/components/hook/class.flagship-hook.php on line 38
[15-Sep-2016 15:11:33 UTC] PHP Notice:  Undefined index: setup.actions in /var/www/website_path/wp-content/plugins/flagship-for-woocommerce/includes/components/hook/class.flagship-hook.php on line 38
[15-Sep-2016 15:11:33 UTC] PHP Notice:  Undefined index: metabox.actions in /var/www/website_path/wp-content/plugins/flagship-for-woocommerce/includes/components/hook/class.flagship-hook.php on line 38
[15-Sep-2016 15:11:34 UTC] PHP Notice:  Undefined index: settings.filters in /var/www/website_path/wp-content/plugins/flagship-for-woocommerce/includes/components/hook/class.flagship-hook.php on line 38

```

**Comment by yi-FLS** [comment]
@dlaramee  you could check the lastest version v0.1.12. It is fixed.

**Comment by dlaramee** [comment]
@yi-FLS Was already on 0.1.12 ... Just removed the whole plugin folder and re-uploaded to be 100% sure I was only have the 0.1.12 files and the PHP Notice are still showing in the error.log file.

**Comment by patrick-fls** [comment]
@dlaramee Can you confirm which version of woocommerce you're using? Thank you

**Comment by dlaramee** [comment]
@patrick-fls Running: Woocommerce 2.6.4 under WordPress 4.6.1

**Comment by patrick-fls** [comment]
@dlaramee Unfortunately we do not support 2.6 at this time, only 2.5. Support for 2.6 is in the works with this ticket https://github.com/flagshipcompany/flagship-for-woocommerce/issues/21
