### ISSUE TITLE
Shipping Markup $ unable to set full dollar amount (ie can't set 3.50 only 3 or 4) 

### ISSUE THREAD

**Issue by Red-Cross-Knight** [flagshipcompany/flagship-for-woocommerce#66]
Unable to use partial numbers in shipping markup column.  Accepts only whole numbers.
Following configuration gives error:
![image](https://user-images.githubusercontent.com/1887734/89944327-9c0c3800-dbed-11ea-9de1-686ccfd40d4b.png)
Error Message 
![image](https://user-images.githubusercontent.com/1887734/89944377-b6461600-dbed-11ea-8652-4cf56970ab23.png)

Setting to 3 or 4 works fine. even using 3.00 is accepted. 

Running version 2.0.18

**Comment by radua** [comment]
@Red-Cross-Knight We have updated the plugin to address this issue. Please update to version 2.0.19.

**Comment by Red-Cross-Knight** [comment]
Still getting the same error.

Versons: 
Wordpress - 5.3.4
WooCommerce - 3.9.2
Flagship - 2.0.19

**Comment by radua** [comment]
Hi Red-Cross-Knight,
It is working fine for us.
![image](https://user-images.githubusercontent.com/14368934/90154631-591aa380-dd58-11ea-8861-26c29c0599bf.png)

![image](https://user-images.githubusercontent.com/14368934/90155497-65ebc700-dd59-11ea-98f6-92eb0e6b36f3.png)

**Comment by Red-Cross-Knight** [comment]
This is only working on when you select to add a new box, does not work on existing boxes.  Also once set using a new box, cannot be modifed, get the same error as before (must be whole number)
